### ISSUE TITLE
Migration diffs keep creating same migration

### ISSUE THREAD

**Issue by kirkbushell** [laravel-doctrine/migrations#24]
Hey there!

Weird thing going on when I run doctrine:migrations:diff without making any changes - it makes the same migration over and over. 

This is the migration that it keeps making:

``` php
<?php

namespace Database\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema as Schema;

class Version20160315014046 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('ALTER TABLE players ALTER buildings TYPE JSON');
        $this->addSql('ALTER TABLE players ALTER buildings DROP DEFAULT');
        $this->addSql('ALTER TABLE players ALTER research TYPE JSON');
        $this->addSql('ALTER TABLE players ALTER research DROP DEFAULT');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE players ALTER buildings TYPE JSON');
        $this->addSql('ALTER TABLE players ALTER buildings DROP DEFAULT');
        $this->addSql('ALTER TABLE players ALTER research TYPE JSON');
        $this->addSql('ALTER TABLE players ALTER research DROP DEFAULT');
    }
}
```

Here's the YAML file:

``` yaml
# IronSteel.Game.Player.Player.dcm.yml
IronSteel\Game\Player\Player:
  type: entity
  table: players
  repositoryClass: IronSteel\Game\Player\PlayerRepository

  id:
    playerId:
      type: uuid

  fields:
    username:
      type: string

    email:
      type: string
      length: 100
      unique: true

    iron:
      type: integer
      options:
        unsigned: true
        default: 0

    gas:
      type: integer
      options:
        unsigned: true
        default: 0

    vapor:
      type: integer
      options:
        unsigned: true
        default: 0

    buildings:
      type: json
      nullable: true

    research:
      type: json
      nullable: true

    createdAt:
      column: created_at
      type: datetime

    updatedAt:
      column: updated_at
      type: datetime
      nullable: true
```
